CREATE TABLE IF NOT EXISTS editor_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_salt CHAR(32) NOT NULL,
  password_hash CHAR(128) NOT NULL,
  role ENUM('viewer','editor','admin') NOT NULL DEFAULT 'editor',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS editor_map_documents (
  map_id INT UNSIGNED NOT NULL PRIMARY KEY,
  document_json LONGTEXT NOT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  author VARCHAR(100) NOT NULL,
  thumbnail_png LONGBLOB NULL,
  cell_thumbnail_png LONGBLOB NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS editor_map_versions (
  map_id INT UNSIGNED NOT NULL,
  version INT UNSIGNED NOT NULL,
  document_json LONGTEXT NOT NULL,
  author VARCHAR(100) NOT NULL,
  saved_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (map_id, version),
  CONSTRAINT fk_editor_version_document FOREIGN KEY (map_id) REFERENCES editor_map_documents(map_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS editor_locks (
  map_id INT UNSIGNED NOT NULL PRIMARY KEY,
  owner VARCHAR(100) NOT NULL,
  expires_at DATETIME(3) NOT NULL,
  CONSTRAINT fk_editor_lock_document FOREIGN KEY (map_id) REFERENCES editor_map_documents(map_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS editor_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  actor VARCHAR(100) NOT NULL,
  action VARCHAR(80) NOT NULL,
  map_id INT UNSIGNED NULL,
  details_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_audit_map_time (map_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS editor_map_backups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  map_id INT UNSIGNED NOT NULL,
  editor_version INT UNSIGNED NOT NULL,
  snapshot_json LONGTEXT NOT NULL,
  actor VARCHAR(100) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX idx_backup_map_time (map_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
